### ISSUE TITLE
Adjacency matrices must not contain self edges

### ISSUE THREAD

**Issue by DesiKeki** [cvxgrp/pymde#13]
Using following example on my dataset:

```
embedding = pymde.preserve_neighbors(tensor_df_x, embedding_dim=2, verbose=True).embed()
pymde.plot(embedding, color_by=df_train['intent'])
```

Getting following error:

`ValueError: ('Adjacency matrices must not contain self edges; the following nodes were found to have self edges: ', array([ 34,  44, 110, 120, 153, 171, 181]))`

The dataset is https://drive.google.com/file/d/1bHi3hmfFRUE_wwqoTyHuUhd7LrdC4Pag/view?usp=sharing

**Comment by akshayka** [comment]
Thanks for reporting, and for being a very early user of PyMDE! I will take a look.

**Comment by akshayka** [comment]
I have found the cause of the issue. I am working on a fix, which will be uploaded to PyPI as a new version later today.

By the way, I thought I might let you know that some columns in your dataframe are duplicates of each other. For example, rows 34 and 35 in the dataframe (loaded from the attached CSV) are the same. This leads to an error in my code, which did not anticipate duplicated items.

In general, when embedding, you shouldn't include duplicates of items.

**Comment by akshayka** [comment]
A fix for this issue has been merged into the main branch. I'll upload a new version of PyMDE soon, to PyPI.

Here's some code and sample output using our data, with this fix:

```python3
import pandas as pd
import pymde
import torch

df = pd.read_csv('/home/akshay/Downloads/df_train.csv')
training_data = df.drop(['Unnamed: 0', 'intent'], axis=1)
training_data = torch.tensor(training_data.to_numpy())
mde = pymde.preserve_neighbors(
    training_data, embedding_dim=2, verbose=True)
mde.embed(verbose=True)
mde.plot(color_by=df['intent'], marker_size=5.)
```

![image](https://user-images.githubusercontent.com/1994308/112664153-e35ed600-8e16-11eb-8181-c4748ee429c2.png)

You can play around with the parameters to `preserve_neighbors` (eg, add `constraint=pymde.Standardized()`, use different penalties, change the number of `n_neighbors` to see how these different components affect the quality of your embedding).

**Comment by akshayka** [comment]
@DesiKeki a new version has been uploaded to PyPI. Install it with `pip install --upgrade pymde`. Let me know if you ran into further issues, and thanks again for reporting this bug, and for being one of PyMDE's first users!

**Comment by DesiKeki** [comment]
Thanks a lot for the quick fix and response @akshayka
