### ISSUE TITLE
Can't show the image using PyCharm

### ISSUE THREAD

**Issue by lyf7115** [cvxgrp/pymde#18]
I install the pymde in PyCharm,for the beginning example with MNIST.
I use pymde.plot(embedding, color_by=mnist.attributes['digits']),but I can't see the visualization result.
I don't kown where I am wrong,can you help me?

Here is my code:
```python3
import pymde
import torchvision

mnist = pymde.datasets.MNIST()

embedding = pymde.preserve_neighbors(mnist.data, verbose=True).embed(verbose=True)
print('embedding shape === ',embedding.shape)
pymde.plot(embedding, color_by=mnist.attributes['digits'])
```

**Comment by lyf7115** [comment]
Thanks,now it's going well.

**Comment by akshayka** [comment]
Great! Glad it works. I'll close this issue, then.
