### ISSUE TITLE
module `requests` not found

### ISSUE THREAD

**Issue by mfansler** [cvxgrp/pymde#21]
The Datasets functionality is partially dependent on the `requests` package through `torchvision.datasets`. However, `torchvision` doesn't consider that to be essential functionality, so `requests` is not an explicit dependency. This leads users who create a minimal environment, e.g.

```bash
conda create -n foo -c conda-forge pymde
```

to encounter a ModuleNotFound error when trying an example like

```python
import pymde

mnist = pymde.datasets.MNIST()
```

Not a huge deal, but if following suit with `torchvision` and not including `requests` as an explicit dependency, it might be nice to give users a heads up in the documentation.

**Comment by akshayka** [comment]
Thanks for reporting! I've created a PR that includes requests as a dependency. The MNIST example should work out of the box.
