### ISSUE TITLE
does pymde handle missing data?

### ISSUE THREAD

**Issue by turmeric-blend** [cvxgrp/pymde#33]
Hi, this is an interesting library :) I have one question, does `pymde` handle missing data?

For example, for `data` of shape `(n_items, n_features)` as input into ` pymde.preserve_neighbors(data)`, some  `n_features` may be `nan`.

**Comment by akshayka** [comment]
Hey, thanks for your interest in PyMDE!

Missing data is tricky. The high-level functions (`preserve_neighbors` and `preserve_distances`) cannot handle missing data. Missing data can mean different things in different contexts, so these high-level functions simply don't have enough information about how to interpret missing data, and how to compare, say, a row (example) with missing feature values with another row.

So if you have missing data, you have a couple options. You can impute the missing values yourself, using any number of matrix completion methods, then pass your data matrix to `preserve_neighbors`. Or, you could [wire up your own MDE problem](https://pymde.org/mde/index.html), from scratch (which would require you to come up with pairs of items known to be similar).

If you share more specifics about your application, I might be able to give you more targeted advice.

**Comment by turmeric-blend** [comment]
I have store items data like type of item (with categories and sub categories), price, sales, which typical region of consumers buys them... etc.

I want to visualize them in clusters and potentially generate input features (encompassing the relationship between store items) using `pymde` and feed it into a machine learning model.

**Comment by akshayka** [comment]
@turmeric-blend , so sorry for the late response, I missed your follow up. 

PyMDE won't be able to handle missing values for you. Your best bet is to come up with a custom MDE problem, using your own "metric" that can account for your missing values.
