### ISSUE TITLE
[docs] Update example in documentation

### ISSUE THREAD

**Issue by theresekoch** [cvxgrp/pymde#35]
I noticed a typo in the example in the MDE>Distortion functions>Losses section of the documentation (https://pymde.org/mde/index.html#losses) .  The second line of the example reads `f = pymde.losses.Quadratic(weights)`, when it should read `f = pymde.losses.Quadratic(deviations)`. 

I'm happy to fix this by forking the repo and submitting a pull request. Is that ok? Should I go ahead and do the same if I notice any other small errors?

**Comment by akshayka** [comment]
@theresekoch, thanks so much for catching this typo and reporting it. 

Yes, please do submit a PR, for this and for any other mistakes you find. That would be very much appreciated.

Thanks!

**Comment by theresekoch** [comment]
No problem! Here is a link to the pull request https://github.com/cvxgrp/pymde/pull/36.
