### ISSUE TITLE
Nearest Neighbor edges are not consistent between runs

### ISSUE THREAD

**Issue by jstankowicz** [cvxgrp/pymde#42]
Hello,
Running `pymde.preserve_neighbors` does not always produce the same set of edges as stored in `mde.edges`.
Here is a MWE:
```python
import pymde
import torch
n_examples=15 # Note results become reproducible with n_examples=14
embedding_dim = 2
original_dim = 128
X = torch.rand((n_examples,original_dim))
collect = []
for i in range(5):
    mde = pymde.preserve_neighbors(X,embedding_dim=embedding_dim)
    collect.append(mde.edges)
    if i > 0:
        print(f"Trial {i} matches trial {i-1}")
        print((torch.sort(collect[i],0).values == torch.sort(collect[i-1],0).values).all())
        print()
```
This prints:
```python
Trial 1 matches trial 0
tensor(False)

Trial 2 matches trial 1
tensor(False)

Trial 3 matches trial 2
tensor(False)

Trial 4 matches trial 3
tensor(False)
```
Note per the comment above, if I switch to `n_examples = 14`, I get that all elements of `collect` are identical.

I haven't been able to fully trace the issue, but did note that the `neighbors` variable defined [here](https://github.com/cvxgrp/pymde/blob/eae362946cfc1be07d94eaf03673b8e1de1fa7de/pymde/preprocess/data_matrix.py#L144) is consistent on each trial, so my best guess is there is something strange happening in the `Graph` class [here](https://github.com/cvxgrp/pymde/blob/eae362946cfc1be07d94eaf03673b8e1de1fa7de/pymde/preprocess/data_matrix.py#L178).

**Comment by akshayka** [comment]
Thanks for reporting, and for the great MWE! I'll take a look.

**Comment by akshayka** [comment]
@jstankowicz,

I took a look.

`pymde.preserve_neighbors` randomly subsamples from the neighborhood graph.

Right now PyMDE doesn't have an API for setting the random seed (I plan to add one, see issue #43). For now, you can get deterministic behavior by setting two random seeds (one for PyTorch, one for NumPy) before calling `preserve_neighbors`:

```python3
import pymde
import torch
import numpy as np


n_examples=15 # Note results become reproducible with n_examples=14
embedding_dim = 2
original_dim = 128
X = torch.rand((n_examples,original_dim))
collect = []
for i in range(5):
    torch.manual_seed(0)
    np.random.seed(0)
    mde = pymde.preserve_neighbors(X,embedding_dim=embedding_dim)
    collect.append(mde.edges)
    if i > 0:
        print(f"Trial {i} matches trial {i-1}")
        print((torch.sort(collect[i],0).values == torch.sort(collect[i-1],0).values).all())
        print()
```

prints

```
Trial 1 matches trial 0
tensor(True)

Trial 2 matches trial 1
tensor(True)

Trial 3 matches trial 2
tensor(True)

Trial 4 matches trial 3
tensor(True)
```

Let me know if that helps?

**Comment by akshayka** [comment]
Alternatively, you can disable the inclusion of repulsive distortion functions, which will make the neighborhood computation deterministic.

Note the kwarg `repulsive_penalty` below. Setting it to `None` disables repulsion.

```python3
n_examples=15 # Note results become reproducible with n_examples=14              
embedding_dim = 2                                                                
original_dim = 128                                                               
X = torch.rand((n_examples,original_dim)).double()                               
collect = []                                                                     
for i in range(5):                                                               
    mde = pymde.preserve_neighbors(X, embedding_dim=embedding_dim,               
            repulsive_penalty=None)                                              
    collect.append(mde.edges)                                                    
    if i > 0:                                                                    
        print(f"Trial {i} matches trial {i-1}")                                  
        print((torch.sort(collect[i],0).values == torch.sort(collect[i-1],0).values).all())
        print()    
```

**Comment by jstankowicz** [comment]
Thanks for taking a look at this! Like you guessed, I was looking into this for random-seed-setting purposes. Interestingly the random-seed-setting doesn't work for 36 examples:
```python
import pymde
import torch
import numpy as np
from graph_embeddings.tools import set_random_seed
n_examples=36
embedding_dim = 2
original_dim = 128
collect = []
def set_seed(i):
    torch.manual_seed(i)
    np.random.seed(i)
X = torch.rand((n_examples,original_dim))
for i in range(5):
    set_seed(0)
    mde = pymde.preserve_neighbors(X,embedding_dim=embedding_dim)#, repulsive_penalty=None)
    collect.append(mde.edges)
    if i > 0:
        print(f"Trial {i} matches trial {i-1}")
        print((torch.sort(collect[i],0).values == torch.sort(collect[i-1],0).values).all())
        print()
```
returns:
```python
Trial 1 matches trial 0
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
/tmp/ipykernel_13917/3102527318.py in <module>
     15     if i > 0:
     16         print(f"Trial {i} matches trial {i-1}")
---> 17         print((torch.sort(collect[i],0).values == torch.sort(collect[i-1],0).values).all())
     18         print()

RuntimeError: The size of tensor a (226) must match the size of tensor b (223) at non-singleton dimension 0
```
If I traced it through correctly, looks like that might result from swapping from `sklearn` (for 35 and fewer examples) to `pynndescent` (for more than 35 examples), and `pynndescent` can return differing numbers of nearest neighbors (although why the cutoff is 35 examples is unclear to me).

At any rate the `mde.preserve_neighbors(...,repulsive_penalty=None,...)` option works for me:
```python
import pymde
import torch
import numpy as np
from graph_embeddings.tools import set_random_seed
n_examples=36
embedding_dim = 2
original_dim = 128
collect = []
def set_seed(i):
    torch.manual_seed(i)
    np.random.seed(i)
X = torch.rand((n_examples,original_dim))
for i in range(5):
    set_seed(0)
    mde = pymde.preserve_neighbors(X,embedding_dim=embedding_dim, repulsive_penalty=None)
    collect.append(mde.edges)
    if i > 0:
        print(f"Trial {i} matches trial {i-1}")
        print((torch.sort(collect[i],0).values == torch.sort(collect[i-1],0).values).all())
        print()
```
returns
```python
Trial 1 matches trial 0
tensor(True)

Trial 2 matches trial 1
tensor(True)

Trial 3 matches trial 2
tensor(True)

Trial 4 matches trial 3
tensor(True)
```

**Comment by akshayka** [comment]
@jstankowicz, thanks so much for the follow up, and sorry for the late reply! I was out on vacation.

I've created a fix (https://github.com/cvxgrp/pymde/pull/45) which I believe solves this issue.

The above PR adds a function, `pymde.seed`, which lets you set a global random seed. (It sets the NumPy and torch global seeds, and initializes a NumPy generator for later use by internal PyMDE code. This last bit was required to get your example working.)

To set the seed to 0, you'd just call

```python3
pymde.seed(0)
```

Does that API look good to you?

**Comment by jstankowicz** [comment]
No worries, thanks for diving into this! I pulled the `random_seed` branch, and confirmed that `pymde.seed(0)` indeed resolves all the issues above. Thanks!

**Comment by akshayka** [comment]
Great! Thanks again for raising the issue and providing helpful code snippets.

I'll merge the PR soon and cut a new release. Once that's done, I'll close this issue.
