### ISSUE TITLE
Build on Conda Forge

### ISSUE THREAD

**Issue by akshayka** [cvxgrp/pymde#5]
It would be awesome to build PyMDE on Conda Forge.

I would appreciate some help with this, since I don't have experience uploading to Conda Forge.

@mfansler, if you're still interested in helping, that would be much appreciated.

**Comment by mfansler** [comment]
Am happy to help. My idea was to try a simple PyPI downstream feedstock, which shouldn't need any changes here (other than that license in the tar.gz on PyPI). For a first pass, I would try a grayskull-based recipe and see if that works. If so, additional build customization could then be done from the feedstock.

Does that sound good? Would you want to be included as a maintainer on the Conda Forge feedstock?

**Comment by akshayka** [comment]
That sounds good to me! And yes, please add me as a maintainer. Thank you!

**Comment by mfansler** [comment]
Here's [the PR on Conda Forge](https://github.com/conda-forge/staged-recipes/pull/14383/). It's currently running through CI and hopefully it just works. For now I copied the license from here, but in the future we can have it pull directly from the PyPI tarball. I used a short paragraph from the README for the description (Anaconda Cloud doesn't support a rendered version).

@akshayka have a look over the recipe to verify it looks okay and please comment if anything doesn't make sense. CF also likes if all the maintainers comment that they approve being included.

**Comment by mfansler** [comment]
Finally went through!

https://github.com/conda-forge/pymde-feedstock

**Comment by mfansler** [comment]
If you're interested in adding badges to this README, there are some examples in [the feedstock README](https://github.com/conda-forge/pymde-feedstock#current-release-info), as well as [ones from Anaconda Cloud](https://anaconda.org/conda-forge/pymde/badges).

[![Conda Version](https://img.shields.io/conda/vn/conda-forge/pymde.svg)](https://anaconda.org/conda-forge/pymde)
