### ISSUE TITLE
Continuous color bar for categorical variables

### ISSUE THREAD

**Issue by kyleford8** [cvxgrp/pymde#51]
First off, cool package! I've noticed that when I supply categorical arrays to "color_by" I still end up with a continuous color bar in my figure. I'm using pymde version 0.1.2 with python 3.9.7, pandas 1.3.4, and numpy 1.20.3. Hardware is an M1 MacBook Pro. I've checked that I'm actually using variables which are categorical, but otherwise haven't been able to figure out why I always get a smooth color bar. From perusing the code it looks like if the object I use for "color_by" is discrete, I should automatically get a discrete colorbar, right? All of my data are stored as a pandas dataframe, which I have been coercing into numpy objects. 

Code snippet:

```
print(plotframe.head())
embedding = pymde.preserve_distances(plotframe.T.to_numpy(), embedding_dim=2, verbose=True).embed()
test = np.array(plotframe.columns)
print(np.issubdtype(test.dtype, np.object_))
pymde.plot(embedding, color_by=test, marker_size=10)
plt.tight_layout()
plt.savefig("MDE_test")
plt.close('all')
```

Output:
       Liver     Brain  Pancreas  ...     Spleen     Kidney    Muscle
0  10.809978  6.798201  5.420175  ...  11.332651  13.995842  2.141489
1  14.133262  8.006512  0.000000  ...  10.533630  11.486465  0.000000
2  11.177152  3.051282  5.471645  ...  12.835654   8.657145  2.040094
3  12.226920  3.475457  0.000000  ...   9.413930   8.958743  1.973367
4   9.611370  0.000000  0.000000  ...   6.384823   4.735076  0.000000
[5 rows x 9 columns]

Feb 21 10:54:16 AM: Computing 36 distances

True

![MDE_test](https://user-images.githubusercontent.com/67128320/155011729-b69bcd32-9a0d-47fa-9568-06327561103f.png)

**Comment by akshayka** [comment]
You're right, you should get a discrete colorbar. I tried a few examples on my own machine (using strings and ints) and got discrete colorbars as expected.

Can you include the value of `test` so I can take a look?

**Comment by kyleford8** [comment]
Sure, the values of test are:
```
print(test)
```
Output: ['Liver' 'Brain' 'Pancreas' 'Heart' 'Lung' 'Intestine' 'Spleen' 'Kidney'
 'Muscle']

I've also tested it with a toy example with an array defined using a list strings, yielding the same result.
```
print(plotframe.head())
embedding = pymde.preserve_distances(plotframe.T.to_numpy(), embedding_dim=2, verbose=True).embed
# test = np.array(plotframe.columns)
test = np.array(["Hello","Foo","Bar","Plz","Work","Hi","Discrete","Values","Strings"])
print(np.issubdtype(test.dtype, np.object_))
pymde.plot(embedding, color_by=test, marker_size=10)
plt.tight_layout()
plt.savefig("MDE_test")
plt.close('all')
```
![MDE_test](https://user-images.githubusercontent.com/67128320/155185809-1fb5d6b5-d905-4fc1-8451-d9b8d43d991d.png)

Interestingly, when I try using the MNIST dataset from the example notebooks, I get the same result.

```
import pymde
import matplotlib.pyplot as plt

mnist = pymde.datasets.MNIST()
embedding = pymde.preserve_neighbors(mnist.data).embed(verbose=True)
pymde.plot(embedding, color_by=mnist.attributes['digits'])
plt.tight_layout()
plt.savefig("MDE_test2")
plt.close('all')
```

![MDE_test2](https://user-images.githubusercontent.com/67128320/155186969-4c1ccacb-eac8-4e1e-9cea-667a7952371b.png)

**Comment by akshayka** [comment]
Wow, it's curious that the MNIST example doesn't work for you. That works for me locally, and on colab: https://colab.research.google.com/drive/1FZmKL-_fNrAHswBWFQzWvULcDFWFLlvX?usp=sharing

What version of matplotlib are you using?

I noticed that you're using an old version of PyMDE (0.1.2, the latest is 0.1.14). You might want to upgrade (though I can't reproduce this bug even on 0.1.2).

**Comment by kyleford8** [comment]
I'm using matplotlib 3.5.1. Doing a fresh install in a clean conda environment (with just PyMDE  0.1.14 + dependencies) produces plots with the correct behavior, as does updating to PyMDE 0.1.14 in my existing environment. Not sure what the underlying problem is (since it wasn't reproducible on your machine or colab), but marking as closed since there's a simple working solution. Thanks for all of your help!
