### ISSUE TITLE
Quadratic initialization on GPU

### ISSUE THREAD

**Issue by adamgayoso** [cvxgrp/pymde#54]
The quadratic initialization takes the most time for a dataset with 150k observations and 15 nearest neighbors. Is it possible to use the GPU for this?

PyTorch has support for both CUDA-backed COO matrices and [lobpcg](https://pytorch.org/docs/stable/generated/torch.lobpcg.html). See sparse supported linear algebra [operations](https://pytorch.org/docs/stable/sparse.html#supported-linear-algebra-operations).

**Comment by akshayka** [comment]
> PyTorch has support for both CUDA-backed COO matrices and [lobpcg](https://pytorch.org/docs/stable/generated/torch.lobpcg.html). See sparse supported linear algebra [operations](https://pytorch.org/docs/stable/sparse.html#supported-linear-algebra-operations).

Oh, that's awesome! I wasn't aware that sparse support had become this mature.

I'm definitely open to having this in PyMDE.

**Comment by adamgayoso** [comment]
I could maybe try to implement it, but even if it was in there, it seems like it's not accessible through `preserve_neighbors` (`cg=True`) option for quadratic init
