### ISSUE TITLE
Updating embeddings Notebook - doesnt work 

### ISSUE THREAD

**Issue by TobiasKonradsen** [cvxgrp/pymde#58]
Hallo, have recently looked into this cool library, and wanted to do some embedding. 

But have trouble running the updating embeddings notebook.
https://github.com/cvxgrp/pymde/blob/main/examples/updating_an_existing_embedding.ipynb

 When I do this step:

incremental_mde = pymde.preserve_neighbors(
    mnist.data,
    constraint=anchor_constraint,
    init='random',
    verbose=False)
  
 I get the  this error:
   
![image](https://user-images.githubusercontent.com/43344305/160474100-003afcfe-4e01-4758-b8aa-32c34e11702a.png)

Am running on a clean environment.

Reproduced the error in this 10 lines colab file: https://colab.research.google.com/drive/1Fq4u8Z85Xmpz1Z3YKem7jA2ONfGouAiA?usp=sharing

Hope you can help.

Kind regards

**Comment by akshayka** [comment]
Thanks for reporting! working on a fix

**Comment by akshayka** [comment]
I've pushed a fix, and a new version should be uploaded to PyPI & conda forge soon (0.1.15) that contains this fix. I'll close this issue when the new version lands.

**Comment by akshayka** [comment]
The fix is available on PyPI now, and will be on conda forge soon, as version 0.1.15.

Thank you for reporting this issue!
