### ISSUE TITLE
incompatibility with PyTorch 2.0?

### ISSUE THREAD

**Issue by PierreBoyeau** [cvxgrp/pymde#76]
Hi, many thanks for the wonderful package. I have observed that I get segmentation fault errors when using PyTorch 2.0 and pymde. Everything works fine with PyTorch 1.13.1. Would it be possible to pin torch accordingly?

**Comment by akshayka** [comment]
@PierreBoyeau Are you still finding pymde to be incompatible with 2.0? If so we should keep this issue open

**Comment by PierreBoyeau** [comment]
@akshayka : I was not able to reproduce on a fresh environment, so I am not exactly sure which conflict caused the seg fault. I will update you if I have more info.
