### ISSUE TITLE
Single cell example errors.

### ISSUE THREAD

**Issue by jacobhurst** [cvxgrp/pymde#9]
SolverError: Function evaluation returned NaN.

mde2 = pymde.preserve_neighbors(
    scrna_wilk.data,
    embedding_dim=3,
    constraint=pymde.Standardized(),
    repulsive_fraction=1.0,
    verbose=True,
)
embedding2 = mde2.embed(verbose=True)

This code produces the following output:-

---------------------------------------------------------------------------
SolverError                               Traceback (most recent call last)
<ipython-input-20-95ce8e8b57ec> in <module>
      6     verbose=True,
      7 )
----> 8 embedding2 = mde2.embed(verbose=True)

~/.local/lib/python3.8/site-packages/pymde/problem.py in embed(self, X, eps, max_iter, memory_size, verbose, print_every, snapshot_every)
    494             )
    495         else:
--> 496             X_star, solve_stats = optim.lbfgs(
    497                 X=X,
    498                 constraint=self.constraint,

~/.local/lib/python3.8/site-packages/pymde/optim.py in lbfgs(X, objective_fn, constraint, eps, max_iter, memory_size, use_line_search, use_cached_loss, verbose, print_every, snapshot_every, logger)
    129             norm_X = X.norm(p="fro")
    130         X.requires_grad_(True)
--> 131         opt.step(value_and_grad)
    132         X.requires_grad_(False)
    133 

/apps/easybuild/1.0/software/PyTorch/1.6.0/lib/python3.8/site-packages/torch/autograd/grad_mode.py in decorate_context(*args, **kwargs)
     13         def decorate_context(*args, **kwargs):
     14             with self:
---> 15                 return func(*args, **kwargs)
     16         return decorate_context
     17 

~/.local/lib/python3.8/site-packages/pymde/lbfgs.py in step(self, closure)
    514                             closure, x, t, d, self._project_callback)
    515 
--> 516                     loss, flat_grad, t, ls_func_evals = _strong_wolfe(
    517                         obj_func, x_init, t, d, loss, flat_grad, gtd)
    518                 self._cached_loss = torch.tensor(loss, device=flat_grad.device)

~/.local/lib/python3.8/site-packages/pymde/lbfgs.py in _strong_wolfe(obj_func, x, t, d, f, g, gtd, c1, c2, tolerance_change, max_ls)
     71             torch.isnan(g_new).any() or
     72             torch.isinf(g_new).any()):
---> 73         raise SolverError("Function evaluation returned NaN.")
     74     ls_func_evals = 1
     75     gtd_new = g_new.dot(d)

SolverError: Function evaluation returned NaN.

**Comment by akshayka** [comment]
Whoa, thanks for raising this issue! Will take a look.

**Comment by jacobhurst** [comment]
thanks! pretty excited about the package, particularly the ability to interact with the graph of the embedding which i think it will help with.

**Comment by akshayka** [comment]
I just ran your code snippet, and it worked without error on my machine. However, I am using PyTorch 1.8.0, while it appears you are using 1.6.0.

I downgraded my torch installation to 1.6.0, and reran your code. And perplexingly, it worked again.

![image](https://user-images.githubusercontent.com/1994308/112500169-61eb4300-8d45-11eb-99c9-5c4a01455699.png)

**Can you try two things for me?**

1. Immediately after constructing `mde2`, can you execute `print((mde2.distances(mde2._X_init) == 0).any())`  and tell me what the output is?
2. If possible, can you try upgrading torch, running again, and seeing if anything changes?

**Comment by jacobhurst** [comment]
print((mde2.distances(mde2._X_init) ==0).any())

produces:- 

tensor(False)

**Comment by jacobhurst** [comment]
I will do the upgrade as you suggest..

**Comment by akshayka** [comment]
My guess is a few of the distances are very small, which can lead to an error in evaluating the repulsive penalty (`pymde.penalties.log`).

If that is indeed the case, then I may have a fix. Will provide an update on this thread soon.

**Comment by jacobhurst** [comment]
I've upgraded torch and got the similar output as yourself. Thanks for your help!

**Comment by akshayka** [comment]
Great! For others who are facing this issue: it should (hopefully) be addressed by PyMDE version 0.1.4, which was just uploaded to PyPI moments ago.
